// Expo config plugin: Android release signing.
//
// WHY THIS EXISTS: the android/ directory is gitignored and regenerated by
// `expo prebuild` (Continuous Native Generation). Any signing config added by
// hand to android/app/build.gradle or android/gradle.properties is DESTROYED by
// `expo prebuild --clean`. This plugin re-injects it on every prebuild, reading
// the secret credentials from credentials/keystore.json — a gitignored file that
// lives OUTSIDE android/, so it (and credentials/upload.keystore) survive prebuild.
//
// To rotate/replace the keystore: drop a new credentials/upload.keystore and
// update credentials/keystore.json, then re-run prebuild. Nothing else to touch.

const { withAppBuildGradle, withGradleProperties } = require('expo/config-plugins');
const fs = require('fs');
const path = require('path');

// --- exact-match anchors from the Expo SDK 56 Android template ---------------
const OLD_SIGNING = `    signingConfigs {
        debug {
            storeFile file('debug.keystore')
            storePassword 'android'
            keyAlias 'androiddebugkey'
            keyPassword 'android'
        }
    }`;

const NEW_SIGNING = `    signingConfigs {
        debug {
            storeFile file('debug.keystore')
            storePassword 'android'
            keyAlias 'androiddebugkey'
            keyPassword 'android'
        }
        release {
            // Injected by plugins/withReleaseSigning.js. Do not edit generated
            // android/ files — edit the plugin or credentials/keystore.json.
            if (project.hasProperty('KREDITS_UPLOAD_STORE_FILE')) {
                storeFile file(KREDITS_UPLOAD_STORE_FILE)
                storePassword KREDITS_UPLOAD_STORE_PASSWORD
                keyAlias KREDITS_UPLOAD_KEY_ALIAS
                keyPassword KREDITS_UPLOAD_KEY_PASSWORD
            }
        }
    }`;

const OLD_BUILDTYPE = `        release {
            // Caution! In production, you need to generate your own keystore file.
            // see https://reactnative.dev/docs/signed-apk-android.
            signingConfig signingConfigs.debug`;

const NEW_BUILDTYPE = `        release {
            signingConfig signingConfigs.release`;

function loadCredentials(projectRoot) {
  const p = path.join(projectRoot, 'credentials', 'keystore.json');
  if (!fs.existsSync(p)) return null;
  try {
    return JSON.parse(fs.readFileSync(p, 'utf8'));
  } catch (e) {
    console.warn('[withReleaseSigning] could not parse credentials/keystore.json:', e.message);
    return null;
  }
}

const withReleaseSigning = (config) => {
  // 1) Add the release signingConfig block + point buildTypes.release at it.
  config = withAppBuildGradle(config, (cfg) => {
    if (cfg.modResults.language !== 'groovy') return cfg;
    let src = cfg.modResults.contents;

    if (src.includes(OLD_SIGNING)) {
      src = src.replace(OLD_SIGNING, NEW_SIGNING);
    } else if (!src.includes('KREDITS_UPLOAD_STORE_FILE')) {
      console.warn(
        '[withReleaseSigning] debug signingConfigs anchor not found — the RN ' +
          'template may have changed; release signing was NOT injected.'
      );
    }

    if (src.includes(OLD_BUILDTYPE)) {
      src = src.replace(OLD_BUILDTYPE, NEW_BUILDTYPE);
    }

    cfg.modResults.contents = src;
    return cfg;
  });

  // 2) Feed the credentials into gradle.properties (both files are gitignored).
  config = withGradleProperties(config, (cfg) => {
    const creds = loadCredentials(cfg.modRequest.projectRoot);
    if (!creds) {
      console.warn(
        '[withReleaseSigning] credentials/keystore.json missing — release build ' +
          'will fall back to unsigned. Create it to sign the release .aab.'
      );
      return cfg;
    }
    const storeFile = path.join(cfg.modRequest.projectRoot, 'credentials', 'upload.keystore');
    const props = {
      KREDITS_UPLOAD_STORE_FILE: storeFile,
      KREDITS_UPLOAD_KEY_ALIAS: creds.keyAlias,
      KREDITS_UPLOAD_STORE_PASSWORD: creds.storePassword,
      KREDITS_UPLOAD_KEY_PASSWORD: creds.keyPassword,
    };
    for (const [key, value] of Object.entries(props)) {
      const existing = cfg.modResults.find((i) => i.type === 'property' && i.key === key);
      if (existing) existing.value = value;
      else cfg.modResults.push({ type: 'property', key, value });
    }
    return cfg;
  });

  return config;
};

module.exports = withReleaseSigning;
